export class InvitationNotFoundError extends Error {
  constructor() {
    super('O convite n√£o foi encontrado.')
  }
}
